import { Spinner } from '@components/ui/Spinner'
import { useAuth } from '@store/auth'
import { useElectoralProcess } from '@store/electoralProcess'
import { useFilterProcesses } from '@store/filterProcess'
import { useFilterStats } from '@store/filterStats'
import { useSelectedProcess } from '@store/selectedProcess'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { ReactNode, useEffect } from 'react'
interface AuthLayoutProps {
  children: ReactNode
}
export const AuthLayout = ({ children }: AuthLayoutProps) => {
  const { isLoading, isAuth, refreshAuth } = useAuth()
  const { electoralProcess, refreshElectoralProcess } = useElectoralProcess()
  const { refreshFilterProcesses } = useFilterProcesses()
  const { refreshFilterProcesses: refreshFilterStats } = useFilterStats()
  const { refreshSelectedProcess } = useSelectedProcess()

  useEffect(() => {
    refreshAuth()
    refreshElectoralProcess()
    // refreshFilterProcesses()
    // refreshFilterStats()
    // refreshSelectedProcess()
  }, [])

  const router = useRouter()
  useEffect(() => {
    if (!isLoading) {
      if (isAuth) {
        if (electoralProcess) {
          router.push('/')
        } else {
          router.push('/processes')
        }
      }
    }
  }, [isLoading, isAuth])

  if (isLoading || isAuth) return <Spinner />
  return (
    <>
      <Head>
        <title>Login | PAS</title>
        <meta name="description" content="Generated by Monitoreo de PAS" />
      </Head>
      <div className="grid w-screen h-screen place-content-center">{children}</div>
    </>
  )
}
