import '../styles/globals.css'
import 'antd/dist/antd.css';
import { ReactElement, ReactNode , useEffect} from 'react'
import type { NextPage } from 'next'
import type { AppProps } from 'next/app'
import { ManagedUIContext } from '@components/ui/context';
import Head from 'next/head';
import { GetAuthService, GetTokenAuthService, RemoveSessionAuthService } from 'services/auth/ServiceAuth';
import useAuthStore from 'store/auth/auth';
import { useRouter } from 'next/router';
 
export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement) => ReactNode
}

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout
}

function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const { storeUser , islogged } = useAuthStore();
  const router = useRouter();

   const getLayout = Component.getLayout ?? ((page) => page)

   useEffect(()=>{
    const tkn = GetTokenAuthService() 
    const {  user } = GetAuthService()
    if(tkn){
      if(user?.profile == 'admin'){
        router.push("listadoacceso");
      } 
      storeUser(user)
    }else{
        router.push("/auth");
        RemoveSessionAuthService()
    }

   },[ router.asPath ])
   
   
  return (
   <>
    <Head>
    <title>Monitoreo de PAS2</title>
    <meta name="description" content="Generated by Monitoreo de PAS" />
    <link rel="icon" href="/favicon.ico" />
    <script src="css/arbol.css" async ></script>
  </Head>
    <ManagedUIContext pageProps={pageProps}>
      {getLayout(<Component {...pageProps} />)}
    </ManagedUIContext>
   </>
  )
}

export default MyApp
