import { DetailCard, DetailCardPay, LayoutFirst } from '@components/common'
import api from '@framework/api'
import { useQuery } from '@tanstack/react-query'
import { Card } from 'antd'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { ReactElement, useEffect, useState } from 'react'
import { IDetailItem, IPropsItem } from './detallepas'
import { IDetailPay } from '@framework/types/processes.interface'

const DetailPay = () => {
  const router = useRouter()
  const id: string = String(router?.query?.id ?? '')
  const typepay: string = String(router?.query?.typepay ?? '')

  const [dataItem, setDataItem] = useState<IPropsItem>()
  // const {
  //   data: data,
  //   isLoading,
  //   isError,
  //   refetch
  // } = useQuery<{ processes: IDetailItem[] }>({
  //   queryKey: ['processes'],
  //   queryFn: () => api.listpas.getProcessesByTracking(Number(id)),
  //   retry: false,
  //   refetchOnWindowFocus: false,
  //   enabled: !!id
  // })

  const { data: pay } = useQuery({
    queryKey: ['getPay'],
    queryFn: () => api.payments.getPay(id),
    retry: false,
    refetchOnWindowFocus: false,
    enabled: !!id
  })

  const pays = pay
    ?.map((i: IDetailItem | IDetailPay) => {
      let date
      if ('payment_date' in i) {
        date = new Date(i.payment_date)
      }
      if ('created_at_dt' in i) {
        date = new Date(i.created_at_dt)
      }
      return { ...i, date }
    })
    .sort((a: any, b: any) => a.date.getTime() - b.date.getTime())

  useEffect(() => {
    const itemDetailPay = localStorage.getItem('itemDetailPay')
    const resItemDetailPay = itemDetailPay ? JSON.parse(itemDetailPay) : {}
    setDataItem(resItemDetailPay)
  }, [])

  const detailEmi = pays?.filter((item: any) => item.tracking_action === 'EMISION')[0]
  const arrayNoti = pays?.filter((item: any) => item.tracking_action === 'NOTIFICACION')
  const headerName = `${dataItem?.name} - R.G. ${dataItem?.resolution_number} - Exp. ${dataItem?.num_expediente}`

  const dataRemake =
    id && pays && pays?.length > 0 ? pays?.filter((item: any) => item.rj_type === 'REHACER' && item.rj_remake)[0] : ({} as IDetailItem)

  const rj_remakeDatail: IDetailItem = dataRemake

  return (
    <>
      <Head>
        <title>Detalle PAS | Monitoreo de PAS</title>
        <meta name="description" content="Generated by Monitoreo de PAS" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Card title="">
        <div style={{ marginBottom: '0.4rem' }}>
          <h1 style={{ fontSize: 25, color: '#4F5172' }}>{headerName}</h1>
        </div>

        <hr style={{ marginBottom: '0.9rem', borderTop: '2px solid #A8CFEB' }} />

        {rj_remakeDatail?.document && (
          <p className="text-xl">Los registros con (*) quedan sin efecto por Resolución Jefatural {rj_remakeDatail?.document}.</p>
        )}

        {typepay && (
          <p className="text-xl">
            El tipo de pago registrado en el expediente es: <span className="uppercase">{typepay}</span>{' '}
          </p>
        )}

        <div className="relative h-full p-10 overflow-hidden wrap">
          <div className="absolute h-full border border-2 border-gray-700 border-opacity-20" style={{ left: '50%' }}></div>
          {id &&
            pays?.map((item: any, key: any) => {
              if (!item?.payment_date) {
                return (
                  <DetailCard
                    key={key}
                    par={(key + 1) % 2 === 0}
                    item={{ ...item, headerName }}
                    idx={key}
                    estado=""
                    detailEmi={detailEmi}
                    arrayNoti={arrayNoti}
                    onHidden={() => {}}
                    //   onHidden={() => {
                    //     getDetailInfo(id!)
                    //   }}
                  />
                )
              } else {
                return (
                  <DetailCardPay
                    key={key}
                    par={(key + 1) % 2 === 0}
                    item={{ ...item, headerName }}
                    idx={key}
                    estado=""
                    detailEmi={detailEmi}
                    arrayNoti={arrayNoti}
                    onHidden={() => {}}
                  />
                )
              }
            })}
        </div>
        <hr style={{ marginBottom: '0.9rem', borderTop: '2px solid #A8CFEB' }} />
        <div style={{ display: 'flex', gap: '50px' }}>
          <button
            className="text-white bg-[#2596be] rounded-[10px] cursor-pointer text-[1rem] py-2.5 px-[60px]"
            onClick={() => router.push('/listadopasgad')}>
            Regresar
          </button>
        </div>
      </Card>
    </>
  )
}

DetailPay.getLayout = function getLayout(page: ReactElement) {
  return <LayoutFirst>{page}</LayoutFirst>
}

export default DetailPay
