import Head from "next/head";
import { Button, Select } from "antd";
import React, { ReactElement } from "react";
import { LayoutFirst } from "@components/common";
import { NextPageWithLayout } from "pages/_app";
import { Card } from "@components/ui";
import "moment/locale/es";
import "react-resizable/css/styles.css"; // Importa los estilos de react-resizable
import { SearchOutlined } from "@ant-design/icons";

interface EstadisticaProps {
  pageNum: number;
  pageSize: number;
  total: number;
}

interface IPropsItem {
  actualizacion: string;
  etapa: string | number | null;
  fecha_fin: string | null;
  fecha_inicio: string | null;
  name: string;
  numero: number;
  resolution_number: string | null;
  responsable: string | null;
  type: string | null;
  estado_proceso: string | null;
  sgd: boolean;
}

const Estadistica: NextPageWithLayout<EstadisticaProps> = ({ pageNum, pageSize, total }) => {
  const options = [
    {
      value: "todos",
      label: "Todos",
    },
    {
      value: "hola2",
      label: "Hola2",
    },
    {
      value: "hola3",
      label: "Hola3",
    },
  ];

  return (
    <>
      <Head>
        <title>Listado de PAS | Monitoreo de PAS</title>
        <meta name="description" content="Generated by Monitoreo de PAS" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card title="Listado de personal de ODPE" border={false}>
        <div>
          <h2 className="text-[#2B3674] text-lg font-semibold">Elecciones Regionales y Municipales 2022</h2>
          <hr style={{ marginTop: "10px", borderTop: "2px solid #A8CFEB" }} />
        </div>

        <div className="pt-8  pb-4 flex gap-[17px] w-full items-center">
          <div className="flex flex-col mb-5 font-poppins">
            <p className="mb-3 ml-2 text-md font-semibold text[#333333]">Cargo</p>
            <Select style={{ width: 160 }} placeholder="Cargo" options={options} />
          </div>
          <div className="flex flex-col mb-5">
            <p className="mb-3 ml-2 text-md font-semibold text[#333333]">Departamento</p>
            <Select style={{ width: 160 }} placeholder="Departamento" options={options} />
          </div>
          <div className="flex flex-col mb-5">
            <p className="mb-3 ml-2 text-md font-semibold text[#333333]">Provincia</p>
            <Select style={{ width: 160 }} placeholder="Provincia" options={options} />
          </div>
          <div className="flex flex-col mb-5">
            <p className="mb-3 ml-2 text-md font-semibold text[#333333]">Distrito</p>
            <Select style={{ width: 160 }} placeholder="Distrito" options={options} />
          </div>
          <div className="flex flex-col mb-5">
            <p className="mb-3 ml-2 text-md font-semibold text[#333333]">Org. Política</p>
            <Select style={{ width: 160 }} placeholder="Org. Política" options={options} />
          </div>
          <div className="flex flex-col mb-5">
            <Button className="flex justify-center items-center w-14 mt-8">
              <SearchOutlined />
            </Button>
          </div>
        </div>
      </Card>
    </>
  );
};

Estadistica.getLayout = function getLayout(page: ReactElement) {
  return <LayoutFirst>{page}</LayoutFirst>;
};

export default Estadistica;
